### ISSUE TITLE
Bug Report: Missing "./client" specifier in "@dub/better-auth" package

### ISSUE THREAD

**Issue by kais-radwan** [dubinc/dub-better-auth#1]
# Missing Client Export for Better-Auth Integration

## Summary

The `@dub/better-auth` package documentation references a client-side plugin (`dubAnalyticsClient`) that should be exported from `@dub/better-auth/client`, but this export doesn't exist in the current package structure.

## Environment

- **Package Version**: `@dub/better-auth@^0.0.2`
- **Better-Auth Version**: `better-auth@^1.2.7` 
- **Package Manager**: Bun
- **Framework**: TanStack Start with React 19+

## Expected Behavior

According to the documentation, I should be able to:

1. Import the client-side plugin:
   ```typescript
   import { dubAnalyticsClient } from "@dub/better-auth/client";
   ```

2. Use it in the better-auth client configuration:
   ```typescript
   import { createAuthClient } from "better-auth/react";
   
   const authClient = createAuthClient({
     baseURL: import.meta.env.VITE_BASE_URL,
     plugins: [
       dubAnalyticsClient(),
       // other plugins...
     ],
   });
   ```

## Actual Behavior

The import fails with the following TypeScript error:
```
Cannot find module '@dub/better-auth/client' or its corresponding type declarations.
```

And:

```
[plugin:vite:import-analysis] Missing "./client" specifier in "@dub/better-auth" package
```

## Steps to Reproduce

1. Install `@dub/better-auth@^0.0.2`
2. Try to import `dubAnalyticsClient` from `@dub/better-auth/client`
3. Observe the TypeScript error

## Issue Analysis

Looking at the package structure, it appears that:
1. The server-side export exists: `@dub/better-auth` ✅
2. The client-side export is missing: `@dub/better-auth/client` ❌
3. The documentation references the client export but it's not implemented

## Impact

This prevents proper integration of Dub analytics on the client-side of better-auth applications.

## Additional Context

- This is blocking our implementation of analytics tracking in our Tanstack/better-auth application

## Package.json Dependencies

```json
{
  "@dub/better-auth": "^0.0.2",
  "better-auth": "^1.2.7",
  "dub": "^0.63.4",
  "react": "^19.1.0",
  "vite": "^6.3.5",
}
```

**Comment by steven-tey** [comment]
@kais-radwan we just published `@dub/better-auth@0.0.3` which should fix this – can you confirm?

**Comment by decentparadox** [comment]
I am using `"@dub/better-auth": "^0.0.6"` and I am still getting the same issue

> 
Better-Auth Version: better-auth@^1.3.34
Package Manager: pnpm
Framework: Nextjs with React 19+

**Comment by decentparadox** [comment]
I rebuilt this repo, and it appears that `dubAnalyticsClient` isn’t being exported anywhere.

<img width="855" height="466" alt="Image" src="https://github.com/user-attachments/assets/e66059ba-b182-4eed-aeae-7861a2e3b9ba" />

please reopen the issue
